---
#######################
#Deploying ELK Stack
#
#######################

- hosts: localhost
  connection: local
  tasks:
    - name: Copy elastcisearch yaml from cloned path to role files directory
      copy:
        src: "{{ playbook_dir }}/ELKFiles/elasticsearch.yaml"
        dest: "{{ playbook_dir }}/roles/elasticsearch/files"
    - name: Copy filebeat yaml files from cloned path to role files directory
      copy:
        src: "{{ playbook_dir }}/ELKFiles/{{ item }}"
        dest: "{{ playbook_dir }}/roles/filebeat/files"
      with_items:
        - filebeatConfig.yaml
        - filebeat.yaml
    - name: Copy logstash yaml files from cloned path to role files directory
      copy:
        src: "{{ playbook_dir }}/ELKFiles/{{ item }}"
        dest: "{{ playbook_dir }}/roles/logstash/files"
      with_items:
        - logstashConfig.yaml
        - logstash.yaml
    - name: Copy kibana yaml from cloned path to role files directory
      copy:
        src: "{{ playbook_dir }}/ELKFiles/kibana.yaml"
        dest: "{{ playbook_dir }}/roles/kibana/files"
    - name: Set default namespace
      shell: "kubectl config use-context dev"
        
- hosts: worker
  gather_facts: true
  become: true
  roles:
    - init

- hosts: controller
  gather_facts: true
  become: true
  roles:
    - elasticsearch
    - filebeat
    - logstash
    - kibana
